### PR TITLE
Windows symlink fix and typescript conversion

### PR DESCRIPTION
**Pull request by williamluke4**
I have not tested this on Mac or Linux

### CODE REVIEW

**Comment by adrianmcli** [comment]
@williamluke4 thanks for this! I'm going to test this out tomorrow and hopefully merge it soon.

**Comment by adrianmcli** [comment]
@williamluke4 actually, can I ask a favour of you? I'd like to consider the symlink fix and typescript integration separately. I think adding Typescript is going to be a bit too opinionated, but that's something we can discuss. But I don't want that to stop the symlink fix being merged.

**Comment by williamluke4** [comment]
@adrianmcli Will do it when i have time. I don't really see any reason why people would be against typescript as there doesn't have to be any differences... It is just there if you want to have a better development experience

**Comment by williamluke4** [comment]
@adrianmcli Have you had time to test it yet?

**Comment by adrianmcli** [comment]
@williamluke4 I don't think Typescript is appropriate for this project right now. And your symlink fix seems to be using a relative import that reaches outside of the `client` folder. This doesn't work on Mac OS X/Linux, which is why I used a symlink to begin with. In other words, we need to keep the symlink mechanism.

I'll be closing this PR for now, but don't hesitate to make an issue for discussion or submit another PR that you think I might accept given what I've stated above. Thanks for your effort!

**Pull request closed without merging**
