### PR TITLE
added ether balance

### LINKED ISSUE #20: Show usage of web3
The dapp page currently does not demonstrate use of `web3`. Perhaps we can add a `getEthBalance()` method in the component class to get the amount of ETH stored in the first account. It might look something like this:

```js
getEthBalance = async () => {
  const { web3, accounts } = this.props
  const balanceInWei = await web3.eth.getBalance(accounts[0])
  this.setState({ ethBalance: balanceInWei / 1e18 })
}
```

Of course, we must remember to pass in web3:

```jsx
<Web3Container
  renderLoading={() => <div>Loading Dapp Page...</div>}
  render={({ accounts, contract, web3 }) => (
    <Dapp accounts={accounts} contract={contract} web3={web3} />
  )}
/>
```

### PR DESCRIPTION
**Pull request by lightswarm124**
Fixes #20 
Added a ".bind(this)" to help update state variables

### CODE REVIEW

**Comment by adrianmcli** [comment]
As far as I'm aware, `.bind(this)` is not necessary because we are using the class properties syntax of defining methods.

**Comment by adrianmcli** [comment]
Also, we should probably also convert `balanceInWei` into units of `ETH`.

**Comment by lightswarm124** [comment]
One *small* issue with converting balanceInWei to Eth units is that it rounds the last decimals (I believe this may be due to the size capacity of decimals in JS). Small cosmetic issue, but everything else works

**Comment by adrianmcli** [comment]
Sorry for the late reply, I'll try to look at this this weekend.

**Comment by adrianmcli** [comment]
Thanks @lightswarm124

**Pull request merged**
